# -*- coding: utf-8 -*-
"""Scraper_Telenoticias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QY6vYeKjCALOeARfbOW-RBgFK74wiQhm

### Importación de librerías
"""

from bs4 import BeautifulSoup
import requests

"""### Medio que vamos a scrapear"""

url = 'https://www.teletica.com/noticias/coronavirus'
telenoticias = requests.get(url)
telenoticias.status_code

telenoticias.request.headers

"""### Parseamos la dirección y declaramos el soup"""

soup = BeautifulSoup(telenoticias.text, 'lxml')

"""### Noticia principal"""

coronavirus = soup.find('div', attrs={'class':'area area-temp-20'})
cabeza1 = coronavirus.find('a', attrs = {'class':'nota-link'})            
cabeza1.text

"""### Sección media de noticias (3 noticias)"""

noticia_abajo = soup.find('div', attrs={'class':'area area-temp-30'})
noticias_abajo = noticia_abajo('a', attrs={'class':'nota-link'})

noticias_abajo_1 = noticias_abajo[0]
noticias_abajo_2 = noticias_abajo[1]
noticias_abajo_3 = noticias_abajo[2]

print(noticias_abajo_1, noticias_abajo_2, noticias_abajo_3)

"""### Sección de noticias extras (titulos)  | Noticias extras"""

noticias_extra = soup.find('div', attrs = {'class': 'sector sector-list-news'})
noticias_extra1 = noticias_extra.find('div', attrs = {'class':'holder'}).find_all('h2')
noticias_extra1

"""### Links de las noticias extras | Noticias extras"""

noticias_extra = soup.find('div', attrs = {'class': 'sector sector-list-news'})
noticias_extra1 = noticias_extra.find('div', attrs = {'class':'holder'}).find_all('a')

noticia_extra_1 = noticias_extra1[0].get('href')
noticia_extra_2 = noticias_extra1[1].get('href')
noticia_extra_3 = noticias_extra1[2].get('href')
noticia_extra_4 = noticias_extra1[3].get('href')
noticia_extra_5 = noticias_extra1[4].get('href')
noticia_extra_6 = noticias_extra1[5].get('href')
noticia_extra_7 = noticias_extra1[6].get('href')
noticia_extra_8 = noticias_extra1[7].get('href')


print(noticia_extra_1)
print(noticia_extra_2)
print(noticia_extra_3)
print(noticia_extra_4)
print(noticia_extra_5)
print(noticia_extra_6)
print(noticia_extra_7)
print(noticia_extra_8)